services:
  api1:
    image: gugagoncalves/rinha-2026-nim:v8
    platform: linux/amd64
    cpuset: "0"
    network_mode: "none"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      memlock: -1
    environment:
      API_SOCKET_PREFIX: /sock/api1
      API_WORKERS: "1"
      MLOCK: "1"
      EPOLL_SPIN_US: "0"
      EPOLL_IDLE_US: "5000"
    volumes:
      - sock:/sock
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "165MB"

  api2:
    image: gugagoncalves/rinha-2026-nim:v8
    platform: linux/amd64
    cpuset: "1"
    network_mode: "none"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      memlock: -1
    environment:
      API_SOCKET_PREFIX: /sock/api2
      API_WORKERS: "1"
      MLOCK: "1"
      EPOLL_SPIN_US: "0"
      EPOLL_IDLE_US: "5000"
    volumes:
      - sock:/sock
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "165MB"

  lb:
    image: gugagoncalves/rinha-2026-nim:v8
    platform: linux/amd64
    cpuset: "2,3"
    entrypoint: ["/lb"]
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment:
      LB_PORT: "9999"
      LB_BACKLOG: "65535"
      LB_ACCEPT_BATCH: "128"
      API_SOCKETS: "/sock/api1-w0.sock,/sock/api2-w0.sock"
    volumes:
      - sock:/sock
    depends_on: [api1, api2]
    ports:
      - "9999:9999"
    networks: [rinha]
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "20MB"

volumes:
  sock:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=4m,uid=0,gid=0,mode=0777"

networks:
  rinha:
    driver: bridge
